table Vendas
	lineageTag: 58a09630-078a-405f-997b-eec78290b087

	column ID_Venda
		dataType: string
		lineageTag: 8fa47ba7-eda7-434e-8d78-561d8c95d647
		summarizeBy: none
		sourceColumn: ID_Venda

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: string
		lineageTag: 15994a3f-1222-4c5b-b147-9bdf6ed6a5ca
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

	column ID_Produto
		dataType: string
		lineageTag: be064ba6-9763-4ede-a286-5494e16f2b48
		summarizeBy: none
		sourceColumn: ID_Produto

		annotation SummarizationSetBy = Automatic

	column ID_Cliente
		dataType: string
		lineageTag: 2b553da2-8667-402e-bcb6-09aafbbac95d
		summarizeBy: none
		sourceColumn: ID_Cliente

		annotation SummarizationSetBy = Automatic

	column ID_Vendedor
		dataType: string
		lineageTag: b355b93e-7441-40f4-9661-5aa3bf633de2
		summarizeBy: none
		sourceColumn: ID_Vendedor

		annotation SummarizationSetBy = Automatic

	column Quantidade
		dataType: string
		lineageTag: 03a84daa-bf68-4ff0-9f60-86bcaa4ced4f
		summarizeBy: none
		sourceColumn: Quantidade

		annotation SummarizationSetBy = Automatic

	column Valor_Unitario
		dataType: double
		lineageTag: cedaaa34-96e7-4ff9-80a5-c09d2625aa28
		summarizeBy: sum
		sourceColumn: Valor_Unitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Vendas = m
		mode: import
		source =
				let
				  Origem = Csv.Document(File.Contents("C:\Users\Nelio\Documents\GitHub\canal-ag-teste\data\raw\Vendas.csv"), [Delimiter = ",", Columns = 7, QuoteStyle = QuoteStyle.None]),
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(Origem, [PromoteAllScalars = true]),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"Valor_Unitario", type number}}, "en-US")
				in
				    #"Tipo Alterado com Localidade"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

