table d_calendario
	lineageTag: bc2d81b6-0ace-48d4-8f76-a2c1bb5984c2

	column DataId
		dataType: dateTime
		formatString: Long Date
		lineageTag: cb48b404-1bb6-4c17-9750-1fd3825d2d98
		summarizeBy: none
		sourceColumn: DataId

		variation Variation
			isDefault
			relationship: 27dcdd83-cfda-41eb-9ef5-fa028875b3fe
			defaultHierarchy: LocalDateTable_b29d074d-15a8-4404-91ac-86d4831a03e8.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 70da7949-7a60-4f22-a618-7476b2da6ce9
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: b737c42a-d98b-4a25-b73e-b66d39e632da
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	column 'Nome dia abreviado'
		dataType: string
		lineageTag: eaeaf78e-45a0-4973-bf9a-82a747d08149
		summarizeBy: none
		sourceColumn: Nome dia abreviado

		annotation SummarizationSetBy = Automatic

	column 'Mes Abreviado'
		dataType: string
		lineageTag: dc3ff431-fe71-47a5-8476-a27fbd027b74
		summarizeBy: none
		sourceColumn: Mes Abreviado

		annotation SummarizationSetBy = Automatic

	partition d_calendario = m
		mode: import
		source = ```
				let
				/*DataMin = List.Min(#"d_fichaFinanceira"[DataPagamento]),*/
				/*DataMax = List.Max(#"d_fichaFinanceira"[DataPagamento]),*/
				/*AnoMin = Date.Year(DataMin), 
				AnoMax = Date.Year(DataMax),*/
				
				DataInicial = List.Min(#"f_vendas"[Data]),
				DataFinal = List.Max(#"f_vendas"[Data]),
				Duracao = Duration.Days(DataFinal - DataInicial) + 1,
				
				    Fonte = List.Dates(DataInicial, Duracao, #duration(1, 0, 0, 0)),
				    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Convertido para Tabela",{{"Column1", type date}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Column1", "Data"}}),
				    #"Ano Inserido" = Table.AddColumn(#"Colunas Renomeadas", "Ano", each Date.Year([Data]), Int64.Type),
				    #"Mes Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([Data]), Int64.Type),
				    #"Trimestre Inserido" = Table.AddColumn(#"Mes Inserido", "Trimestre", each Date.QuarterOfYear([Data]), Int64.Type),
				    #"Semana do Ano Inserido" = Table.AddColumn(#"Trimestre Inserido", "Semana do Ano", each Date.WeekOfYear([Data]), Int64.Type),
				    #"Dia Inserido" = Table.AddColumn(#"Semana do Ano Inserido", "Dia", each Date.Day([Data]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Dia Inserido", "Nome do Mês", each Date.MonthName([Data]), type text),
				    #"Nome do Dia Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Nome do Dia", each Date.DayOfWeekName([Data]), type text),
				    Personalizar1 = Table.RemoveColumns(#"Nome do Dia Inserido",{"Trimestre", "Semana do Ano"}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(Personalizar1, "Semestre", each if [Mês] <= 6 then "Semestre 1" else "Semestre 2"),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"Semestre", type text}}),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Tipo Alterado1", "Trimestre", each if [Mês] <= 3 then "Trimestre 1" else if [Mês] <= 6 then "Trimestre 2" else if [Mês] <= 9 then "Trimestre 3" else "Trimestre 4"),
				    #"Coluna Personalizada Adicionada" = Table.AddColumn(#"Coluna Condicional Adicionada1", "Mes/Ano", each Text.Combine({Text.Start(Text.Proper([Nome do Mês]), 3), "/", Text.From([Ano], "pt-BR")}), type text),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Coluna Personalizada Adicionada",{{"Data", "DataId"}}),
				    #"Primeiros Caracteres Inseridos" = Table.AddColumn(#"Colunas Renomeadas1", "Nome dia abreviado", each Text.Start(Text.Proper([Nome do Dia]), 3), type text),
				    #"Coluna Condicional Adicionada2" = Table.AddColumn(#"Primeiros Caracteres Inseridos", "Nome dia num", each if [Nome dia abreviado] = "Dom" then 1 else if [Nome dia abreviado] = "Seg" then 2 else if [Nome dia abreviado] = "Ter" then 3 else if [Nome dia abreviado] = "Qua" then 4 else if [Nome dia abreviado] = "Qui" then 5 else if [Nome dia abreviado] = "Sex" then 6 else if [Nome dia abreviado] = "Sáb" then 7 else null),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada2",{{"Nome dia num", Int64.Type}, {"Trimestre", type text}}),
				    #"Semana do Ano Inserida" = Table.AddColumn(#"Tipo Alterado2", "Semana do Ano", each Date.WeekOfYear([DataId]), Int64.Type),
				    #"Primeiros Caracteres Inseridos1" = Table.AddColumn(#"Semana do Ano Inserida", "Mes Abreviado", each Text.Start(Text.Proper([Nome do Mês]), 3), type text),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"Primeiros Caracteres Inseridos1",{"Mes Abreviado","Nome dia abreviado","DataId","Dia","Ano"})
				in
				    #"Columns removed by Measure Killer"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

