table f_vendas
	lineageTag: 58a09630-078a-405f-997b-eec78290b087

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 15994a3f-1222-4c5b-b147-9bdf6ed6a5ca
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ID_Produto
		dataType: string
		lineageTag: be064ba6-9763-4ede-a286-5494e16f2b48
		summarizeBy: none
		sourceColumn: ID_Produto

		annotation SummarizationSetBy = Automatic

	column ID_Cliente
		dataType: string
		lineageTag: 2b553da2-8667-402e-bcb6-09aafbbac95d
		summarizeBy: none
		sourceColumn: ID_Cliente

		annotation SummarizationSetBy = Automatic

	column ID_Vendedor
		dataType: string
		lineageTag: b355b93e-7441-40f4-9661-5aa3bf633de2
		summarizeBy: none
		sourceColumn: ID_Vendedor

		annotation SummarizationSetBy = Automatic

	column Quantidade
		dataType: int64
		formatString: 0
		lineageTag: 03a84daa-bf68-4ff0-9f60-86bcaa4ced4f
		summarizeBy: sum
		sourceColumn: Quantidade

		annotation SummarizationSetBy = Automatic

	column Valor_Unitario
		dataType: double
		lineageTag: cedaaa34-96e7-4ff9-80a5-c09d2625aa28
		summarizeBy: sum
		sourceColumn: Valor_Unitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'd_produtos.Nome_Produto'
		dataType: string
		lineageTag: 144487dd-20c5-4342-b88c-37db117c1212
		summarizeBy: none
		sourceColumn: d_produtos.Nome_Produto

		annotation SummarizationSetBy = Automatic

	partition f_vendas = m
		mode: import
		source =
				let
				  Origem = Csv.Document(File.Contents("C:\Users\Nelio\Documents\GitHub\canal-ag-teste\data\raw\Vendas.csv"), [Delimiter = ",", Columns = 7, QuoteStyle = QuoteStyle.None]),
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(Origem, [PromoteAllScalars = true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos",{{"Data", type date}, {"Quantidade", Int64.Type}, {"Valor_Unitario", type number}}, "en-US"),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Tipo Alterado", {"ID_Produto"}, d_produtos, {"ID_Produto"}, "d_produtos", JoinKind.LeftOuter),
				    #"d_produtos Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "d_produtos", {"Nome_Produto"}, {"d_produtos.Nome_Produto"}),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"d_produtos Expandido",{"ID_Cliente","ID_Vendedor","d_produtos.Nome_Produto","Quantidade","ID_Produto","Data","Valor_Unitario"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

